/*
 * Cold Open — topic bank.
 * Plain global array (no build step / module loader needed, so this file
 * works whether index.html is opened directly from disk or served).
 * To add more topics later, just append { category, text } objects below —
 * app.js picks them up automatically.
 */
var COLD_OPEN_TOPICS = [

  // ---------- Technology & AI ----------
  { category: "Technology & AI", text: "Should AI systems be allowed to screen job applicants before any human review?" },
  { category: "Technology & AI", text: "Explain how a recommendation algorithm decides what you see next, to someone who's never thought about it." },
  { category: "Technology & AI", text: "Is it ethical to use AI to generate art in someone else's style?" },
  { category: "Technology & AI", text: "Convince us that smartphones have made us better communicators, not worse." },
  { category: "Technology & AI", text: "Should there be a legal age limit for social media use?" },
  { category: "Technology & AI", text: "What would change if the internet had never been invented?" },
  { category: "Technology & AI", text: "Is privacy already dead, or is that too pessimistic?" },
  { category: "Technology & AI", text: "Describe the app you use most and why it has that much control over your day." },
  { category: "Technology & AI", text: "Should self-driving cars be trusted with life-or-death decisions?" },
  { category: "Technology & AI", text: "Is it better to be a generalist or a specialist in today's job market?" },
  { category: "Technology & AI", text: "Explain why software updates always seem to arrive at the worst time." },
  { category: "Technology & AI", text: "Should companies be required to disclose when you're talking to a chatbot?" },
  { category: "Technology & AI", text: "Is \"digital detox\" a real solution or just a trend?" },
  { category: "Technology & AI", text: "Describe a piece of technology you distrust, and why." },
  { category: "Technology & AI", text: "Should coding be a required subject in every school?" },

  // ---------- Business & Work ----------
  { category: "Business & Work", text: "Is the four-day work week good for productivity?" },
  { category: "Business & Work", text: "Should tipping be replaced by fair wages?" },
  { category: "Business & Work", text: "Convince us that failure is the best teacher in business." },
  { category: "Business & Work", text: "Describe the worst job you've ever had, and what it taught you." },
  { category: "Business & Work", text: "Should remote work be a permanent right, not a perk?" },
  { category: "Business & Work", text: "Is it better to start your own business or climb the ladder at someone else's?" },
  { category: "Business & Work", text: "Explain why a good idea alone is never enough to build a company." },
  { category: "Business & Work", text: "Should CEOs be paid a maximum multiple of their lowest-paid worker's salary?" },
  { category: "Business & Work", text: "Is loyalty to one employer for life outdated advice?" },
  { category: "Business & Work", text: "What makes a meeting worth attending?" },
  { category: "Business & Work", text: "Should unpaid internships be illegal?" },
  { category: "Business & Work", text: "Convince us that a small business you love deserves to be a household name." },
  { category: "Business & Work", text: "Is competition or collaboration the bigger driver of innovation?" },
  { category: "Business & Work", text: "Describe how you'd spend your first day as the new boss." },
  { category: "Business & Work", text: "Should advertising aimed at children be banned outright?" },

  // ---------- Science & Nature ----------
  { category: "Science & Nature", text: "Should space exploration be a higher priority than ocean exploration?" },
  { category: "Science & Nature", text: "Is it ethical to bring back extinct species?" },
  { category: "Science & Nature", text: "Explain photosynthesis to a five-year-old." },
  { category: "Science & Nature", text: "Should zoos exist in the 21st century?" },
  { category: "Science & Nature", text: "Describe the most beautiful natural phenomenon you've witnessed." },
  { category: "Science & Nature", text: "Is curiosity or necessity the real mother of scientific discovery?" },
  { category: "Science & Nature", text: "Should we colonize Mars before fixing Earth's problems?" },
  { category: "Science & Nature", text: "What would happen if bees disappeared for good?" },
  { category: "Science & Nature", text: "Convince us that mushrooms are the most underrated organism on Earth." },
  { category: "Science & Nature", text: "Is it possible to be \"too logical\" as a scientist?" },
  { category: "Science & Nature", text: "Should genetic engineering of human embryos ever be allowed?" },
  { category: "Science & Nature", text: "Explain why the sky is blue, without using the word \"wavelength.\"" },
  { category: "Science & Nature", text: "Describe an animal you think is unfairly feared." },
  { category: "Science & Nature", text: "Should we prioritize funding for climate research over disease research?" },
  { category: "Science & Nature", text: "Is intelligence something we can actually measure fairly?" },

  // ---------- Health & Wellness ----------
  { category: "Health & Wellness", text: "Should mental health days count the same as sick days?" },
  { category: "Health & Wellness", text: "Is the pursuit of a \"perfect\" diet doing more harm than good?" },
  { category: "Health & Wellness", text: "Describe a habit that changed your life, for better or worse." },
  { category: "Health & Wellness", text: "Should therapy be as normalized as going to the dentist?" },
  { category: "Health & Wellness", text: "Convince us that sleep is more important than exercise." },
  { category: "Health & Wellness", text: "Is burnout a personal failure or a systemic one?" },
  { category: "Health & Wellness", text: "Should junk food be taxed like tobacco?" },
  { category: "Health & Wellness", text: "Explain the placebo effect to someone who's never heard of it." },
  { category: "Health & Wellness", text: "Is it healthier to be a morning person or a night owl?" },
  { category: "Health & Wellness", text: "Describe how you'd redesign a hospital waiting room." },
  { category: "Health & Wellness", text: "Should health insurance be tied to your employer at all?" },
  { category: "Health & Wellness", text: "Is \"self-care\" a meaningful idea or a marketing buzzword now?" },
  { category: "Health & Wellness", text: "Should schools start later to match teenagers' sleep cycles?" },
  { category: "Health & Wellness", text: "Convince us that boredom is good for you." },
  { category: "Health & Wellness", text: "Is aging something we should try to cure, or accept?" },

  // ---------- Arts & Culture ----------
  { category: "Arts & Culture", text: "Is nostalgia holding culture back, or is it what keeps culture alive?" },
  { category: "Arts & Culture", text: "Should museums return artifacts to their countries of origin?" },
  { category: "Arts & Culture", text: "Describe a song that changed how you saw the world." },
  { category: "Arts & Culture", text: "Convince us that graffiti is art, not vandalism." },
  { category: "Arts & Culture", text: "Is it possible to separate the art from the artist?" },
  { category: "Arts & Culture", text: "Should AI-generated work be eligible for creative awards?" },
  { category: "Arts & Culture", text: "Explain why a tradition from your culture matters, to someone outside it." },
  { category: "Arts & Culture", text: "Is subtitled film better than dubbed film?" },
  { category: "Arts & Culture", text: "Describe the last piece of art that genuinely surprised you." },
  { category: "Arts & Culture", text: "Should classic literature be rewritten in modern language for new readers?" },
  { category: "Arts & Culture", text: "Is fashion a legitimate art form or just commerce?" },
  { category: "Arts & Culture", text: "Convince us that your hometown has a culture worth visiting for." },
  { category: "Arts & Culture", text: "Should there be a global language, and should it replace local ones?" },
  { category: "Arts & Culture", text: "Is it wrong to enjoy a film or book you know is problematic?" },
  { category: "Arts & Culture", text: "Describe a tradition you think should disappear." },

  // ---------- Philosophy & Ethics ----------
  { category: "Philosophy & Ethics", text: "Is it ever ethical to lie to protect someone's feelings?" },
  { category: "Philosophy & Ethics", text: "What does it actually mean to \"be yourself\"?" },
  { category: "Philosophy & Ethics", text: "Should we judge historical figures by today's moral standards?" },
  { category: "Philosophy & Ethics", text: "Convince us that free will is an illusion — or that it isn't." },
  { category: "Philosophy & Ethics", text: "Is happiness a goal worth chasing directly, or a byproduct of something else?" },
  { category: "Philosophy & Ethics", text: "Describe a moment you changed your mind about something you were sure of." },
  { category: "Philosophy & Ethics", text: "Should there be limits on freedom of speech?" },
  { category: "Philosophy & Ethics", text: "Is it better to be feared or loved as a leader?" },
  { category: "Philosophy & Ethics", text: "What do we actually owe strangers?" },
  { category: "Philosophy & Ethics", text: "Should everyone be required to do a year of public service?" },
  { category: "Philosophy & Ethics", text: "Is it possible to be completely selfless?" },
  { category: "Philosophy & Ethics", text: "Convince us that suffering has value." },
  { category: "Philosophy & Ethics", text: "Should animals have legal rights similar to humans?" },
  { category: "Philosophy & Ethics", text: "Is tradition a good enough reason to keep doing something?" },
  { category: "Philosophy & Ethics", text: "What's the difference between being right and being kind, when you can't be both?" },

  // ---------- Society & Policy ----------
  { category: "Society & Policy", text: "Should college education be free for everyone, regardless of income?" },
  { category: "Society & Policy", text: "Is it fair to inherit wealth you didn't earn?" },
  { category: "Society & Policy", text: "Should voting be mandatory?" },
  { category: "Society & Policy", text: "Convince us that your city needs a law it doesn't currently have." },
  { category: "Society & Policy", text: "Is cancel culture accountability or mob justice?" },
  { category: "Society & Policy", text: "Should prisons focus on punishment or rehabilitation?" },
  { category: "Society & Policy", text: "Describe a rule you'd abolish if you ran your city for a day." },
  { category: "Society & Policy", text: "Is it ethical for countries to have closed borders?" },
  { category: "Society & Policy", text: "Should billionaires be allowed to exist?" },
  { category: "Society & Policy", text: "Is a two-party political system better or worse than a multi-party one?" },
  { category: "Society & Policy", text: "Should juries be replaced by professional judges alone?" },
  { category: "Society & Policy", text: "Convince us that a controversial statue should stay up — or come down." },
  { category: "Society & Policy", text: "Is universal basic income a realistic policy or a fantasy?" },
  { category: "Society & Policy", text: "Should the drinking age be the same as the voting age?" },
  { category: "Society & Policy", text: "Is it the government's job to make people happy?" },

  // ---------- History ----------
  { category: "History", text: "Which invention changed the course of history the most?" },
  { category: "History", text: "Describe a historical event you wish you could have witnessed." },
  { category: "History", text: "Is history written by the winners, and does that matter?" },
  { category: "History", text: "Convince us that a lesser-known historical figure deserves more recognition." },
  { category: "History", text: "Should we still name buildings and streets after flawed historical figures?" },
  { category: "History", text: "What would the modern world look like if the printing press had never existed?" },
  { category: "History", text: "Is progress in history a straight line, or does it move in circles?" },
  { category: "History", text: "Describe the biggest turning point of the last 100 years." },
  { category: "History", text: "Should history be taught chronologically or thematically in schools?" },
  { category: "History", text: "Is it fair to say some empires were \"better\" than others?" },
  { category: "History", text: "Convince us that a specific decade was the most important of the 20th century." },
  { category: "History", text: "What can ancient civilizations teach us that modern ones have forgotten?" },
  { category: "History", text: "Should countries formally apologize for historical wrongs?" },
  { category: "History", text: "Is nostalgia for \"simpler times\" ever historically accurate?" },
  { category: "History", text: "Describe how you think people 200 years from now will judge us." },

  // ---------- Education & Learning ----------
  { category: "Education & Learning", text: "Describe how you'd redesign the school day if you were in charge." },
  { category: "Education & Learning", text: "Should grades be replaced with detailed feedback instead?" },
  { category: "Education & Learning", text: "Is homework actually useful, or just busywork?" },
  { category: "Education & Learning", text: "Convince us that failing a class can be a good thing." },
  { category: "Education & Learning", text: "Should every student learn a second language from childhood?" },
  { category: "Education & Learning", text: "Is standardized testing a fair way to measure ability?" },
  { category: "Education & Learning", text: "Describe the best teacher you ever had, and what made them different." },
  { category: "Education & Learning", text: "Should schools teach financial literacy as a core subject?" },
  { category: "Education & Learning", text: "Is it better to specialize early or explore broadly before choosing a path?" },
  { category: "Education & Learning", text: "Convince us that art class matters as much as math class." },
  { category: "Education & Learning", text: "Should university degrees still matter as much as they used to?" },
  { category: "Education & Learning", text: "Is it possible to teach creativity, or is it something you either have or don't?" },
  { category: "Education & Learning", text: "Describe a subject you wish you'd been taught in school but weren't." },
  { category: "Education & Learning", text: "Should children be allowed to choose what they study, and when?" },
  { category: "Education & Learning", text: "Is learning from failure faster than learning from success?" },

  // ---------- Everyday Life ----------
  { category: "Everyday Life", text: "Convince us pineapple belongs on pizza." },
  { category: "Everyday Life", text: "Describe your ideal Sunday from morning to night." },
  { category: "Everyday Life", text: "Is it rude to check your phone during a conversation?" },
  { category: "Everyday Life", text: "Should tipping culture exist for takeout orders?" },
  { category: "Everyday Life", text: "What's a small daily ritual that makes your life better?" },
  { category: "Everyday Life", text: "Is it better to live in a city or the countryside?" },
  { category: "Everyday Life", text: "Convince us that mornings are better than nights, or the other way around." },
  { category: "Everyday Life", text: "Describe a rule your household has that outsiders would find strange." },
  { category: "Everyday Life", text: "Is it okay to reply to messages days later, or is that rude?" },
  { category: "Everyday Life", text: "What's the most useless item you own that you refuse to throw away?" },
  { category: "Everyday Life", text: "Should public transportation be free everywhere?" },
  { category: "Everyday Life", text: "Describe the last time a stranger's kindness stuck with you." },
  { category: "Everyday Life", text: "Is it better to plan a trip in detail or wing it?" },
  { category: "Everyday Life", text: "Convince us your favorite comfort food deserves more respect." },
  { category: "Everyday Life", text: "What's a habit you inherited from your parents, for better or worse?" },

  // ---------- Entertainment & Pop Culture ----------
  { category: "Entertainment & Pop Culture", text: "Is competitive video gaming a real sport?" },
  { category: "Entertainment & Pop Culture", text: "Should movie spoilers have a statute of limitations?" },
  { category: "Entertainment & Pop Culture", text: "Convince us that reality TV says something real about society." },
  { category: "Entertainment & Pop Culture", text: "Is it better to binge a show in one weekend or savor it weekly?" },
  { category: "Entertainment & Pop Culture", text: "Describe a fictional character you relate to more than you'd like to admit." },
  { category: "Entertainment & Pop Culture", text: "Should streaming platforms bring back weekly episode releases?" },
  { category: "Entertainment & Pop Culture", text: "Is a book always better than its movie adaptation?" },
  { category: "Entertainment & Pop Culture", text: "Convince us that your favorite guilty-pleasure show is actually good." },
  { category: "Entertainment & Pop Culture", text: "Should celebrities be expected to share political opinions?" },
  { category: "Entertainment & Pop Culture", text: "Is fan fiction a legitimate form of storytelling?" },
  { category: "Entertainment & Pop Culture", text: "Describe the last piece of media that made you cry." },
  { category: "Entertainment & Pop Culture", text: "Should award shows still matter in the streaming era?" },
  { category: "Entertainment & Pop Culture", text: "Is nostalgia the main reason reboots keep getting made?" },
  { category: "Entertainment & Pop Culture", text: "Convince us a \"so bad it's good\" movie deserves a rewatch." },
  { category: "Entertainment & Pop Culture", text: "Should social media influencers be considered a real profession?" },

  // ---------- Sports & Games ----------
  { category: "Sports & Games", text: "Should college athletes be paid like professionals?" },
  { category: "Sports & Games", text: "Is chess a sport?" },
  { category: "Sports & Games", text: "Convince us that your favorite underdog team deserved to win." },
  { category: "Sports & Games", text: "Should instant replay be used in every close call, in every sport?" },
  { category: "Sports & Games", text: "Describe the moment you learned what it means to be a good teammate." },
  { category: "Sports & Games", text: "Is it more impressive to win with talent or with grit?" },
  { category: "Sports & Games", text: "Should youth sports keep score, or is that too much pressure too early?" },
  { category: "Sports & Games", text: "Convince us board games are better than video games — or the reverse." },
  { category: "Sports & Games", text: "Is trash talk part of good sportsmanship or against it?" },
  { category: "Sports & Games", text: "Describe a game or sport everyone should try at least once." },
  { category: "Sports & Games", text: "Should athletes be allowed to protest during national anthems?" },
  { category: "Sports & Games", text: "Is a tie a fair result, or should every game have a winner?" },
  { category: "Sports & Games", text: "Convince us that your favorite childhood game deserves a comeback." },
  { category: "Sports & Games", text: "Should esports athletes train the same way traditional athletes do?" },
  { category: "Sports & Games", text: "Is losing gracefully harder than winning gracefully?" },

  // ---------- Environment & Sustainability ----------
  { category: "Environment & Sustainability", text: "Should individuals feel guilty about their carbon footprint, or is that the wrong target?" },
  { category: "Environment & Sustainability", text: "Convince us that one small daily habit can genuinely help the planet." },
  { category: "Environment & Sustainability", text: "Is nuclear energy the most underrated solution to climate change?" },
  { category: "Environment & Sustainability", text: "Should fast fashion be regulated like a hazardous industry?" },
  { category: "Environment & Sustainability", text: "Describe a place in nature you'd fight to protect." },
  { category: "Environment & Sustainability", text: "Is it fair to ask developing countries to limit growth for climate goals set by wealthy ones?" },
  { category: "Environment & Sustainability", text: "Should plastic packaging be banned outright, not just reduced?" },
  { category: "Environment & Sustainability", text: "Convince us that your city needs more green space." },
  { category: "Environment & Sustainability", text: "Is it too late to reverse climate change, or just late enough to still matter?" },
  { category: "Environment & Sustainability", text: "Should companies be legally responsible for the full lifecycle of what they sell?" },
  { category: "Environment & Sustainability", text: "Describe the biggest environmental change you've noticed in your own lifetime." },
  { category: "Environment & Sustainability", text: "Is eating less meat a personal choice or a public responsibility?" },
  { category: "Environment & Sustainability", text: "Should air travel be taxed more heavily to reflect its environmental cost?" },
  { category: "Environment & Sustainability", text: "Convince us a species most people ignore is actually worth saving first." },
  { category: "Environment & Sustainability", text: "Is technology more likely to save us from climate change or distract us from it?" },

  // ---------- Psychology & Relationships ----------
  { category: "Psychology & Relationships", text: "Is it possible to be best friends with someone you rarely talk to?" },
  { category: "Psychology & Relationships", text: "Convince us that arguments can be healthy for a relationship." },
  { category: "Psychology & Relationships", text: "Describe what \"showing up for someone\" really means to you." },
  { category: "Psychology & Relationships", text: "Is it better to confront a conflict directly or let it cool off first?" },
  { category: "Psychology & Relationships", text: "Should you always tell a friend the hard truth, even if they didn't ask?" },
  { category: "Psychology & Relationships", text: "Is it healthier to keep a small circle of friends or a wide one?" },
  { category: "Psychology & Relationships", text: "Describe a time someone's first impression of you was completely wrong." },
  { category: "Psychology & Relationships", text: "Is jealousy ever a useful emotion?" },
  { category: "Psychology & Relationships", text: "Should you forgive someone who never apologizes?" },
  { category: "Psychology & Relationships", text: "Convince us that being alone and being lonely are not the same thing." },
  { category: "Psychology & Relationships", text: "Is it possible to fully know another person?" },
  { category: "Psychology & Relationships", text: "Describe the hardest kind of conversation to have with someone you love." },
  { category: "Psychology & Relationships", text: "Is compromise a sign of strength or of giving in?" },
  { category: "Psychology & Relationships", text: "Should first impressions be trusted, or actively resisted?" },
  { category: "Psychology & Relationships", text: "Convince us that a habit of complaining says more than it seems to." },

  // ---------- Just for Fun / Hypothetical ----------
  { category: "Just for Fun", text: "If you had to give up your phone or your car for a year, which would you choose, and why?" },
  { category: "Just for Fun", text: "Convince us that time travel to the past would go badly within a week." },
  { category: "Just for Fun", text: "What would you do with an extra hour every day that no one else has?" },
  { category: "Just for Fun", text: "If animals could talk for one day, which one would say the most surprising thing?" },
  { category: "Just for Fun", text: "Describe the world if money simply stopped existing tomorrow." },
  { category: "Just for Fun", text: "If you could instantly master one skill, what would you choose and what would you do with it first?" },
  { category: "Just for Fun", text: "Convince us your made-up superpower is actually the most useful one." },
  { category: "Just for Fun", text: "What would change if everyone had to tell the complete truth for 24 hours?" },
  { category: "Just for Fun", text: "If you could relive one ordinary day from your past, which would you pick?" },
  { category: "Just for Fun", text: "Describe the museum exhibit that would be built about your generation." },
  { category: "Just for Fun", text: "If you swapped lives with a stranger for a week, what would surprise them most about yours?" },
  { category: "Just for Fun", text: "Convince us your most controversial food opinion is correct." },
  { category: "Just for Fun", text: "What's a law that exists somewhere that really shouldn't?" },
  { category: "Just for Fun", text: "If your life had a theme song, what would it be and why?" },
  { category: "Just for Fun", text: "Describe the last invention humanity will ever truly need." }

];
